# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='author',
        ),
    ]
