# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_remove_film_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='added_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='labapp.Userus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
