# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_auto_20171223_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.Userus'),
        ),
        migrations.AlterField(
            model_name='userus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
