# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0005_auto_20171223_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='added_by',
        ),
    ]
