# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_remove_film_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userus',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
