# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0011_auto_20171231_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, default='media/def.jpg', upload_to='media/', verbose_name='Афиша'),
        ),
    ]
