# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0012_auto_20180101_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
