# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0013_auto_20180106_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.FileField(default='images/def.jpg', upload_to='images'),
        ),
    ]
